### ISSUE TITLE
DB Table Information Request

### ISSUE THREAD

**Issue by hubuser3976** [Ylgr/broken-whale#2]
Your code suggests I need:
broken_whale.Account
broken_whale.OrderHistory

These are guesses on my part. Could you please supply more detailed info such:
id
type
field length, etc.

Thanks

**Comment by Ylgr** [comment]
just run `npm run migrate` and you will have those tables in your mysql if you setting correctly in .env

**Comment by hubuser3976** [comment]
Great
Thank you
